### PR TITLE
get+query: add columns

### PR DESCRIPTION
**Pull request by sttts**
Making use of https://github.com/upbound/spaces/pull/1434:

Bildschirmfoto 2024-07-19 um 14 08 20

Needs https://github.com/upbound/spaces/pull/1456 for sorting.

### CODE REVIEW

**Comment by sttts** [comment]
They are sorted by creation.

**Comment by sttts** [comment]
Btw, namespaces are a bad example because we have no native resource table columns yet. Try crossplane or providers or so.

**Review by phisco — APPROVED** [review]
Works like a charm now, we'll discuss default sorting separately

**Comment by sttts** [comment]
Follow-ups:
- default sorting
- and in Spaces: add columns for native resources

**Pull request merged**
